---

- name: Edit zabbix server line in config file
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: 'ServerActive=127.0.0.1'
    line: 'ServerActive={{ zabbix_server }}'
  when: inventory_hostname not in groups['local']

- name: Edit zabbix server line in config file
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: 'Server=127.0.0.1'
    line: 'Server={{ zabbix_server }}'
  when: inventory_hostname not in groups['local']

- name: Restart zabbix agent
  shell: /etc/init.d/zabbix-agent restart
