---

- name: Create host groups
  local_action:
    module: zabbix_group
    server_url: http://127.0.0.1/zabbix
    login_user: admin
    login_password: zabbix
    state: present
    host_groups:
      - "{{ item.key }}"
  with_dict: "{{ zabbix_groups }}"

- name: Create a hosts
  local_action:
    module: zabbix_host
    server_url: http://127.0.0.1/zabbix
    login_user: admin
    login_password: zabbix
    host_name: "{{ item.key }}"
    host_groups:
      - "{{ item.value.group }}"
    link_templates:
      - "{{ item.value.template }}"
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ item.value.ip }}"
        dns: ""
        port: 10050
  with_dict: "{{ hosts }}"
